import { useState } from 'react'
import { bids as bidsApi } from '@/api/client'
import { useAsync } from '@/hooks/useAsync'
import { usePolling } from '@/hooks/usePolling'
import { ErrorBanner, Spinner } from '@/components/Primitives'
import { EXPLANATION_LABEL } from '@/lib/labels'
import { formatDateTime } from '@/lib/format'
import type { ExplanationKind } from '@/api/types'
import './ai.css'

/**
 * Generated prose, presented as commentary on a decision that was already
 * made. The verdict comes from the deterministic checks and the consistency
 * report; this panel only describes them. It always sits beside the evidence,
 * never in place of it, and is labelled so a reader cannot mistake it for the
 * decision itself.
 *
 * GET /bids/{id}/explanation returns 404 until narration has run. That is the
 * normal early state, so it renders as "being written", not as an error.
 */
export function AiAssessment({
  bidId, kind = 'ADMIN_SUMMARY', canRegenerate = false,
}: {
  bidId: number
  kind?: ExplanationKind
  canRegenerate?: boolean
}) {
  const [requested, setRequested] = useState(false)
  const exp = useAsync(() => bidsApi.explanation(bidId, kind), [bidId, kind])

  const pending = exp.notFound || requested
  // Only poll while we are waiting for text to appear.
  usePolling(async () => {
    await exp.reload()
    if (exp.data) setRequested(false)
  }, 4000, pending)

  async function regenerate() {
    setRequested(true)
    try {
      await bidsApi.regenerate(bidId, kind)
    } catch (e) {
      setRequested(false)
      throw e
    }
  }

  return (
    <section className="ai-panel">
      <header className="ai-head">
        <div className="row gap2">
          <span className="ai-badge">
            <SparkIcon /> AI-generated
          </span>
          <span className="ai-kind">{EXPLANATION_LABEL[kind]}</span>
        </div>
        {canRegenerate && (
          <button
            className="btn btn-sm"
            onClick={regenerate}
            disabled={pending}
          >
            {pending ? 'Generating…' : 'Regenerate'}
          </button>
        )}
      </header>

      <div className="ai-body">
        {exp.loading && exp.initial && <Spinner label="Loading assessment…" />}

        {!exp.loading && pending && !exp.data && (
          <div className="ai-pending">
            <Spinner />
            <div>
              <div className="strong">Narration is being written</div>
              <div className="small muted">
                The verification result is already final — this is only the
                written summary of it.
              </div>
            </div>
          </div>
        )}

        {exp.error != null && !exp.notFound && (
          <ErrorBanner error={exp.error} onRetry={exp.reload} />
        )}

        {exp.data && (
          <>
            <p className="ai-text">{exp.data.text}</p>
            <footer className="ai-foot">
              <span className="small muted">
                {exp.data.is_fallback
                  ? 'Written from a template — the language model was unavailable.'
                  : `Generated by ${exp.data.model ?? 'the configured model'}.`}
                {' '}Generated {formatDateTime(exp.data.generated_at)}.
              </span>
              <span className="small muted ai-disclaimer">
                This text describes the decision record. It does not produce it.
              </span>
            </footer>
          </>
        )}
      </div>
    </section>
  )
}

function SparkIcon() {
  return (
    <svg width="11" height="11" viewBox="0 0 24 24" fill="currentColor" aria-hidden>
      <path d="M12 2l1.9 5.6L19.5 9.5l-5.6 1.9L12 17l-1.9-5.6L4.5 9.5l5.6-1.9z" />
    </svg>
  )
}
